/***********************************************************************
THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY
DEVELOPER: Zihan Chen(vczh)
***********************************************************************/
#include "Vlpp.h"

#include "..\..\Source\Stream\Interfaces.h"
#include "..\..\Source\Stream\MemoryStream.h"
#include "..\..\Source\Stream\MemoryWrapperStream.h"
#include "..\..\Source\Stream\CharFormat.h"
#include "..\..\Source\FileSystem.h"
#include "..\..\Source\Locale.h"
#include "..\..\Source\Stream\FileStream.h"
#include "..\..\Source\Stream\Accessor.h"
#include "..\..\Source\HttpUtility.h"
#include "..\..\Source\Threading.h"
#include "..\..\Source\Stream\BroadcastStream.h"
#include "..\..\Source\Stream\CacheStream.h"
#include "..\..\Source\Stream\CompressionStream.h"
#include "..\..\Source\Stream\RecorderStream.h"
