/***********************************************************************
THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY
DEVELOPER: Zihan Chen(vczh)
***********************************************************************/
#include "Vlpp.h"

#include "..\..\Source\HttpUtility.h"
#include "..\..\Source\Locale.h"
#include "..\..\Source\Threading.h"
#include "..\..\Source\Stream\Interfaces.h"
#include "..\..\Source\Encoding\Encoding.h"
#include "..\..\Source\Encoding\Base64Encoding.h"
#include "..\..\Source\Encoding\CharFormat\BomEncoding.h"
#include "..\..\Source\Encoding\CharFormat\MbcsEncoding.h"
#include "..\..\Source\Encoding\CharFormat\UtfEncoding.h"
#include "..\..\Source\Encoding\CharFormat\CharFormat.h"
#include "..\..\Source\Encoding\LzwEncoding.h"
#include "..\..\Source\FileSystem.h"
#include "..\..\Source\Stream\BroadcastStream.h"
#include "..\..\Source\Stream\CacheStream.h"
#include "..\..\Source\Stream\EncodingStream.h"
#include "..\..\Source\Stream\FileStream.h"
#include "..\..\Source\Stream\MemoryStream.h"
#include "..\..\Source\Stream\Accessor.h"
#include "..\..\Source\Stream\MemoryWrapperStream.h"
#include "..\..\Source\Stream\RecorderStream.h"
#include "..\..\Source\Stream\Serialization.h"
