/***********************************************************************
THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY
DEVELOPER: Zihan Chen(vczh)
***********************************************************************/
#include "VlppOS.h"
#include "Vlpp.h"

#include "..\..\Source\FileSystem.Windows.cpp"
#include "..\..\Source\HttpUtility.Windows.cpp"
#include "..\..\Source\Locale.Windows.cpp"
#include "..\..\Source\Threading.Windows.cpp"
#include "..\..\Source\Encoding\CharFormat\CharFormat.Windows.cpp"
