/***********************************************************************
THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY
DEVELOPER: Zihan Chen(vczh)
***********************************************************************/
#include "VlppOS.Windows.h"

#include "..\..\Source\FileSystem.Windows.cpp"
#include "..\..\Source\Locale.Windows.cpp"
#include "..\..\Source\Threading.Windows.cpp"
#include "..\..\Source\Encoding\CharFormat\CharFormat.Windows.cpp"
#include "..\..\Source\InterProcess\AsyncSocket\AsyncSocket.Windows.cpp"
#include "..\..\Source\InterProcess\Windows\HttpClient.Windows.cpp"
#include "..\..\Source\InterProcess\Windows\HttpClientApi.Windows.cpp"
#include "..\..\Source\InterProcess\Windows\HttpServer.Windows.cpp"
#include "..\..\Source\InterProcess\Windows\HttpServerApi.Windows.cpp"
#include "..\..\Source\InterProcess\Windows\NamedPipe.Windows.cpp"
#include "..\..\Source\InterProcess\Windows\NetworkProtocol.Windows.cpp"
