/***********************************************************************
THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY
DEVELOPER: Zihan Chen(vczh)
***********************************************************************/
#include "VlppOS.h"

#include "..\..\Source\FileSystem.cpp"
#include "..\..\Source\Locale.cpp"
#include "..\..\Source\Threading.cpp"
#include "..\..\Source\Encoding\Base64Encoding.cpp"
#include "..\..\Source\Encoding\Encoding.cpp"
#include "..\..\Source\Encoding\LzwEncoding.cpp"
#include "..\..\Source\Encoding\CharFormat\BomEncoding.cpp"
#include "..\..\Source\Encoding\CharFormat\CharFormat.cpp"
#include "..\..\Source\Encoding\CharFormat\MbcsEncoding.cpp"
#include "..\..\Source\Encoding\CharFormat\UtfEncoding.cpp"
#include "..\..\Source\Stream\Accessor.cpp"
#include "..\..\Source\Stream\BroadcastStream.cpp"
#include "..\..\Source\Stream\CacheStream.cpp"
#include "..\..\Source\Stream\EncodingStream.cpp"
#include "..\..\Source\Stream\FileStream.cpp"
#include "..\..\Source\Stream\MemoryStream.cpp"
#include "..\..\Source\Stream\MemoryWrapperStream.cpp"
#include "..\..\Source\Stream\RecorderStream.cpp"
