/***********************************************************************
THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY
DEVELOPER: Zihan Chen(vczh)
***********************************************************************/
#include "VlppOS.h"
#include "Vlpp.h"

#include "..\..\Source\InterProcess\Windows\NetworkProtocol.Windows.h"
#include "..\..\Source\InterProcess\Windows\HttpClient.Windows.h"
#include "..\..\Source\InterProcess\Windows\HttpServer.Windows.h"
#include "..\..\Source\InterProcess\Windows\NamedPipe.Windows.h"
